source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'Segment-Mixpanel_Example', :exclusive => true do
  pod "Segment-Mixpanel", :path => "../"
end

target 'Segment-Mixpanel_Tests', :exclusive => true do
  pod "Segment-Mixpanel", :path => "../"

  pod 'OCMockito'
  pod 'Specta'
  pod 'Expecta'
end
