source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

platform :ios, '8.0'

target 'Segment-Mixpanel_Example' do
  pod "Segment-Mixpanel", :path => "../"
end

target 'Segment-Mixpanel_Tests' do
  pod "Segment-Mixpanel", :path => "../"

  pod 'OCMockito', '~> 3.0'
  pod 'Specta'
  pod 'Expecta'
end
