language: objective-c

osx_image: xcode7.3

before_install:
  - gem install cocoapods

script:
# Fails with "Unable to find Analytics/TestFlight".
# - pod lib lint --allow-warnings
  - make xctest

notifications:
  email: false
