source 'https://github.com/CocoaPods/Specs.git'
# use_frameworks!

platform :ios, '8.0'

target 'Segment-Mixpanel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod "Segment-Mixpanel", :path => "../"
end

target 'Segment-MixpanelTests' do
  inherit! :search_paths
  pod "Segment-Mixpanel", :path => "../"
  pod 'OCMockito'
  pod 'Specta'
  pod 'Expecta'
end
